### PR TITLE
Dev acseo

### PR DESCRIPTION
**Pull request by npotier**
Hello @aequasi,

I've been trying and using your project, and I think it's great. I've made some changes for my needs and maybe you would like to integrate them.

Feel free to comment this PR to tell me what you think.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Hey there! Sorry to say i never saw this PR. Looks awesome though!

Is this backwards compatible? Can commands be registered the same way as before?

```yaml
pre-commit:
  - bldr run ci
  - phpunit
  - bin/phpcs
```

**Comment by npotier** [comment]
Hello @aequasi ! Thanks for your reply. I have to say that I also forgot this PR.

Unfortunatelly, I don't think that this is backwards compatible, due to changes in the yaml file. 

I could update my PR in order to make it BC, what do you think ?

**Comment by cryptiklemur** [comment]
That would be awesome. I know people actively use the old style in a bunch of different places and would hate to have to move to another style when its not entirely necessary

**Comment by npotier** [comment]
Hello @aequasi I've updated my PR in order to ensure BC.

Feel free to check it and tell me what you think of it :)

**Comment by cryptiklemur** [comment]
Looks good! Thanks :)

**Pull request merged**
